spring:
  application:
    name: my-blog
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html


logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug